query Categories($ids: [ID]) {
  categories (ids: $ids) {
    ID
    Title
    MapIcon {
      AbsoluteURL
    }
    Children {
      edges {
        node {
          ID
          Identifier
          Title
          MapIcon {
            AbsoluteURL
          }
          Children {
            edges {
              node {
                ID
                Identifier
                Title
                MapIcon {
                  AbsoluteURL
                }
              }
            }
          }
        }
      }
    }
  }
}
