query listingsById(
    $ids: [ID],
    $listingType : String
    ) {

    listingsById(
        ids: $ids
        listingType: $listingType
    ) {
        ID
        Title
        Type
        Featured
        URLSegment
        Identifier
        Website
        Phone
        Email
        MinPrice
        BookingLink
        Latitude
        Longitude
        CurrentStartDate

        MainCategory {
          Identifier
          Title
        }
        MainImage {
            AbsoluteURL
            Loading
            Sized(width: 300, height: 240)
        }
    }
}
