query L ($slug: String, $listingType: String, $startDate: String, $endDate: String, $identifier: Int, $exclude: Int, $categories: [ID], $tags: [ID], $keywords: String, $places: [ID], $longitude: String, $latitude: String, $radius: Int, $dealsOnly: Boolean, $limit: Int, $offset: Int){
  listings (slug: $slug, listingType: $listingType, startDate: $startDate, endDate: $endDate, identifier: $identifier, exclude: $exclude, categories: $categories, tags: $tags, keywords: $keywords, places: $places, longitude: $longitude, latitude: $latitude, radius: $radius, dealsOnly: $dealsOnly, limit: $limit, offset: $offset ) {
    edges {
      node {
        Identifier
        Title
        URLSegment
        Deal
        Shares
        Views
        Favs
        Thumbs
        SharesText
        ViewsText
        FavsText
        ThumbsText
        MainCategory {
          Identifier
          Title
          MapIcon {
            AbsoluteURL
          }
          IconURL
        }
        Categories {
          edges {
            node {
              Title
              Identifier
            }
          }
        }
        Tags {
          edges {
            node {
              Title
              Identifier
            }
          }
        }
        Summary
        Longitude
        Latitude
        Website
        MainImage {
          Title
          AbsoluteURL
          Loading
          Sized(width: 320, height: 240)
        }
      }
    }
    pageInfo {
      hasNextPage
      hasPreviousPage
      totalCount
    }
  }
}
