query ListingTags($id: ID, $hasListings: Boolean, $categories: [ID]) {
    listingtags (id: $id, hasListings: $hasListings, categories: $categories) {
        ID
        Title
        URLSegment
    }
}

