query Locations($id: ID, $ids: [ID], $parentIds: [ID], $all: Boolean) {
    locations(id: $id, ids: $ids, parentIds: $parentIds, all: $all) {
        ID
        Title
        Latitude
        Longitude
        Children {
            edges {
                node {
                    ID
                    Title
                    Latitude
                    Longitude
                }
            }
        }
    }
}
