query TodaysEvents($categoryId: ID, $limit: Int) {
    todaysEvents(categoryId: $categoryId, limit: $limit) {
        Identifier
        Title
        Type
        Featured
        URLSegment
        Summary
        Website
        Phone
        Email
        MinPrice
        BookingLink
        Latitude
        Longitude
        MultipleOccurrences
        CurrentStartDate
        Venue
        StreetAddress
        Suburb
        City
        CurrentPerformace {
            Venue
            StartDate
            EndDate
            FullAddress
            PostalFullAddress
            PhysicalFullAddress
        }
        FuturePerformances {
            Venue
            StartDate
            EndDate
            FullAddress
            PostalFullAddress
            PhysicalFullAddress
        }
        MainImage {
            Title
            AbsoluteURL
            Loading
            Sized(width: 320, height: 240)
        }
        GalleryImages {
            nodes {
                Title
                AbsoluteURL
            }
        }
        MainCategory {
            Identifier
            Title
            MapIcon {
                AbsoluteURL
            }
            IconURL
        }
        Categories {
            edges {
                node {
                    Title
                    Identifier
                }
            }
        }
        Tags {
            edges {
                node {
                    Title
                    Identifier
                }
            }
        }
    }
}
