query TodaysEvents(
    $limit: Int
) {
  todaysEvents(limit: $limit) {
    ID
    Name
    Type
    Featured
    URLSlug
    LimitedSummary
    Identifier
    MapIconPath
    MapIconWidth
    MapIconHeight
    Website
    Phone
    Email
    MinPrice
    BookingURL
    Latitude
    Longitude
    MultipleOccurrences
    CurrentStartDate
    NiceCurrentStartDate
    NiceStartDate
    NiceStartTime
    NiceEndDate
    NiceEndTime
    StartDate
    EndDate
    Venue
    Street
    Suburb
    City
    Image {
      URLForList
      __typename
    }
    MainCategory {
      ID
      Title
    }
    LogoImage {
      URLForList
      __typename
    }
    FutureOccurrences {
      CurrentStartDateNice
      StartDateNice
      StartTimeNice
      EndDateNice
      EndTimeNice
      MultiDays
      __typename
    }
  }
}
